name=INA3221
version=0.0.1
author=cyberphox
maintainer=cyberphox
sentence=INA3221 Triple-Channel Sensor Driver.
paragraph=INA3221 Triple-Channel Sensor Driver.
category=Sensors
url=https://github.com/cyberphox/INA3221
architectures=*
